name: Register Julia Package

on:
  push:
    branches:
      - main
      - master

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Kích hoạt bộ nạp gói Julia Registrator
        uses: julia-actions/register-action@v0.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
