            - name: Register Julia Package
  # You may pin to the exact commit or the version.
  # uses: julia-actions/RegisterAction@d391a7f14ee6db8ad3f8cd26f6da1a6c6fd5b7fb
  uses: julia-actions/RegisterAction@v0.3.2
  with:
    # GitHub API token
    token: ${{ secrets.GITHUB_TOKEN }}
    # Registrator bot username
    registrator: # optional, default is JuliaRegistrator
          
